/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_renderer: (a: number) => void;
export const wasm_start: () => void;
export const wasm_update: () => number;
export const wasm_update_with_message: (a: number, b: number, c: number) => number;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_e9a9d69d95dc72a___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___js_sys_f58b1d8c19b292fc___Array__web_sys_d881da6e64b59126___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___sys__JsOption_wgpu_2ff0625bd2e06ed9___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_e9a9d69d95dc72a___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___sys__JsOption_wgpu_2ff0625bd2e06ed9___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_e9a9d69d95dc72a___JsError___true__11: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___sys__JsOption_wgpu_2ff0625bd2e06ed9___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_e9a9d69d95dc72a___JsError___true__12: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__3: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke___wasm_bindgen_e9a9d69d95dc72a___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e9a9d69d95dc72a___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
